### ISSUE TITLE
USER STORY: 

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#1]
As a **user** I can **view the navigation bar throughout the site** so that **I can easily naviagate between pages from anywhere**

## Acceptance Criteria:

* Acceptance Criteria 1: Navigation bar component is visible at the top of every page
* Acceptance Criteria 2: Navbar contains the following: logo, site name, links to:
 1. home
 2. feed
 3. my events
 4. reviews
 5. profile
 6. signin/out/up

## Tasks:

- [ ] Design navbar component
- [ ] Create HTML, CSS, JSX
- [ ] Test completed functionality
