### ISSUE TITLE
USER STORY: View events linked to one profile

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#10]
As a **user** I can **see all the events from one profile** so that **I can view all the events of one profile easily**

## Acceptance Criteria:

* Acceptance Criteria 1: Filter events by profile 
* Acceptance Criteria 2: Pick out the events of the profile ID which matches the profile page being viewed by the user
* Acceptance Criteria 3: Display the results on the profile page

## Tasks:

- [ ] Design - Profile page
- [ ] Create HTML, CSS, JSX - for profile
- [ ] Create API requests -  get events filtered by viewed profile id
- [ ] Test completed functionality
