### ISSUE TITLE
USER STORY: Create an event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#11]
As a **logged in user** I can **create an event** so that **I can promote an event in the town**

## Acceptance Criteria:

* Acceptance Criteria 1: Add Event button visible on the nav bar when user logged in
* Acceptance Criteria 2: Create event form lets user upload image, and add details of event - title, date, description
* Acceptance Criteria 3: Event title is a required field

## Tasks:

- [ ] Design Create Event Page
- [ ] Create HTML, CSS, JSX - Design form page layout. Get upload photo image
- [ ] Create API requests - set up Post to new event to API 
- [ ] Test completed functionality
