### ISSUE TITLE
USER STORY: Search events list

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#12]
As a **user** I can **search the events list** so that **I can find events that interest me more**

## Acceptance Criteria:

* Acceptance Criteria 1: Search bar above the events list on hompage, feed, and my events page
* Acceptance Criteria 2: Search results shown based on title, tags, username or event_date
* Acceptance Criteria 3: 

## Tasks:

- [ ] Design search bar component
- [ ] Create HTML, CSS, JSX - style search bar 
- [ ] Create API requests - request filtered results based on search input
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
search by event_date not working... need to investigate further

**Comment by quiltingcode** [comment]
search by date working now that i've removed the event_date change date format method from the API. I will attempt to tidy up the frontend render of the date, whilst maintaining the option for the user to search all posts by date as I like this feature
