### ISSUE TITLE
USER STORY: Edit event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#13]
As a **logged in user** I can **edit my own events** so that **change the details or correct mistakes**

## Acceptance Criteria:

* Acceptance Criteria 1: If event profile id matches the logged in user profile id, show edit button next to event on event detail page
* Acceptance Criteria 2: Edit form allows user to change the image, title, description and event date.
* Acceptance Criteria 3:

## Tasks:

- [ ] Design - Edit event page, = pre-populated create event page
- [ ] Create HTML, CSS, JSX -  design the same as the create event page
- [ ] Create API requests - put request to update existing event
- [ ] Test completed functionality
