### ISSUE TITLE
USER STORY: Delete Event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#14]
As a **logged in user** I can **delete my own events** so that **I can remove events from the site**

## Acceptance Criteria:

* Acceptance Criteria 1: If event profile id matches the logged in user profile id, show delete button next to event on event detail page
* Acceptance Criteria 2: Add confirm deletion message for defensive design
* Acceptance Criteria 3: Confirm delete removes event from all lists and from the database

## Tasks:

- [ ] Design - Confirm deletion modal popup
- [ ] Create HTML, CSS, JSX -  
- [ ] Create API requests - destroy request to update existing event
- [ ] Test completed functionality
