### ISSUE TITLE
USER STORY: Add interested to event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#15]
As a **logged in user** I can **add interested to a post** so that **I can publicly display my interest in an event**

## Acceptance Criteria:

* Acceptance Criteria 1: Interested button under all event posts
* Acceptance Criteria 2: Interested button active only when user logged in
* Acceptance Criteria 3: If user not logged in, message on hover tells them they must be logged in to post an interest in an event
* Acceptance Criteria 4: Adding interested increases total interested count for that event

## Tasks:

- [ ] Design - interested button and icon
- [ ] Create HTML, CSS, JSX - set up authentication against logged out users
- [ ] Create API requests - Post interested instance to interested table
- [ ] Test completed functionality
