### ISSUE TITLE
USER STORY: Delete interested 

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#16]
As a **logged in user** I can **remove interested to a post** so that **I can remove interest in an event if i change my mind**

## Acceptance Criteria:

* Acceptance Criteria 1: Interested button under all event posts
* Acceptance Criteria 2: Interested button active only when user logged in
* Acceptance Criteria 3: If user not logged in, message on hover tells them they must be logged in to post an interest in an event
* Acceptance Criteria 4: Deleting interested decreases total interested count for that event

## Tasks:

- [ ] Design - interested button and icon
- [ ] Create HTML, CSS, JSX - set up authentication against logged out users
- [ ] Create API requests - send destroy interested request to API
- [ ] Test completed functionality
