### ISSUE TITLE
USER STORY: Add going to event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#17]
As a **logged in user** I can **add going to an event** so that **I can publicly show that i plan to attend**

## Acceptance Criteria:

* Acceptance Criteria 1: Going button under all event posts
* Acceptance Criteria 2: Going button active only when user logged in
* Acceptance Criteria 3: If user not logged in, message on hover tells them they must be logged in to post going to an event
* Acceptance Criteria 4: Adding going increases total going count for that event

## Tasks:

- [ ] Design - going button and icon
- [ ] Create HTML, CSS, JSX - set up authentication against logged out users
- [ ] Create API requests - Send create going request to API
- [ ] Test completed functionality
