### ISSUE TITLE
USER STORY: View comments relating to one event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#19]
As a **user** I can **view comments of an event** so that **I can see what other users think about the event**

## Acceptance Criteria:

* Acceptance Criteria 1: On Event detail page, view list of all comments relating to that event under the event post
* Acceptance Criteria 2: Comment detail inclue: profile pic and username of comment owner, date posted, comment text
* Acceptance Criteria 3: 

## Tasks:

- [ ] Design - Comment List Component
- [ ] Create HTML, CSS, JSX - colors of username, text, date posted, filter comments by event
- [ ] Create API requests - send request for comments to the API
- [ ] Test completed functionality
