### ISSUE TITLE
USER STORY: Navigation Bar Routes

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#2]
As a **user** I can **click on navigation bar routes, not links** so that **I can move between pages without a page refresh**

## Acceptance Criteria:

* Acceptance Criteria 1: Routes set up on all nav links
* Acceptance Criteria 2: 
* Acceptance Criteria 3:

## Tasks:

- [ ] Create JSX routes for each navbar link
- [ ] Create API requests
- [ ] Test completed functionality
