### ISSUE TITLE
USER STORY: Create comment

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#20]
As a **logged in user** I can **create a comment** so that **I can publicly show my thoughts about an upcoming event**

## Acceptance Criteria:

* Acceptance Criteria 1: Once logged in, create comment form visible under the event details on the event detail page
* Acceptance Criteria 2: Comment is saved against the logged in profile owner
* Acceptance Criteria 3: once the comment is posted successfully, it is visible underneath in the list of comments against the commented event.

## Tasks:

- [ ] Design comment form
- [ ] Create HTML, CSS, JSX - style the form
- [ ] Create API requests -  send form data to the API in a post request
- [ ] Test completed functionality
