### ISSUE TITLE
USER STORY: Edit comment

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#21]
As a **logged in user** I can **edit my comments** so that **I can correct mistakes**

## Acceptance Criteria:

* Acceptance Criteria 1: If user is logged in, and the comment belongs to them, the edit button is available next to the comment
* Acceptance Criteria 2: If user selects edit, comment form is opened up and pre-populated with comment details. (ie. only the comment field can be edited)
* Acceptance Criteria 3: On save, the existing comment is updated

## Tasks:

- [ ] Design
- [ ] Create HTML, CSS, JSX -  pre-populate comment form for editing
- [ ] Create API requests - put request to the API
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
I don't know whether this would look more tidy inside a modal as I don't like the look on the page with the create comment, then the edit comment, then the comment list all one on top of the other. 
I'm going to leave this story as open, the functionality is there now, but if I have time later I may put this edit Comment into a pop up modal instead.
