### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#22]
As a **logged in user** I can **delete a comment that I created** so that **I can remove comments as i see fit**

## Acceptance Criteria:

* Acceptance Criteria 1: Once logged in, user can see the delete button next to all the comments that they created
* Acceptance Criteria 2: Delete button asks for confirmation - for defensive design
* Acceptance Criteria 3: Once confirmed deletion, comment is removed from the comment list and deleted from the database

## Tasks:

- [ ] Design - delete icon
- [ ] Create HTML, CSS, JSX
- [ ] Create API requests - destroy request to API
- [ ] Test completed functionality
