### ISSUE TITLE
USER STORY: Filter events by category

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#23]
As a **user** I can **filter the events list by category** so that **I can easily see all events relating to one particular category**

## Acceptance Criteria:

* Acceptance Criteria 1: Categories pull through from Event model category choices
* Acceptance Criteria 2: Filter dropdown options are visible at the top of the home, feed , reviews and my events page
* Acceptance Criteria 3: Once a category is selected, the events list is filtered to only show events in that category

## Tasks:

- [ ] Design filter dropdown
- [ ] Create HTML, CSS, JSX
- [ ] Create API requests - request filter events list fieldset
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
If you select a category, you then can't return the filter back to all without a page refresh... need to think whether there is a solution to this. Reading bootstrap docs, it doesn't seem to be an obvious possibility. For now, I'm disabling the first option so that it doesn't cause a new onChange reaction on click because this causes a create error and the events can not be loaded and the whirly circle doesn't go away.
