### ISSUE TITLE
USER STORY: Follow another user

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#24]
As a **logged in user** I can **follow another user** so that **I can see their events in my feed page**

## Acceptance Criteria:

* Acceptance Criteria 1: Once logged in, User can see a follow button next to each profile 
* Acceptance Criteria 2: Follow button visible on popular profiles list and on the profile page profile
* Acceptance Criteria 3: On click follow, logged in users following count increases by 1
* Acceptance Criteria 4: On click follow, followed profile followed count goes up by 1

## Tasks:

- [ ] Design  follow button
- [ ] Create HTML, CSS, JSX - toggle button between follow/unfollow on click
- [ ] Create API requests - Create follow request to API
- [ ] Test completed functionality
