### ISSUE TITLE
USER STORY: Unfollow another user

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#25]
As a **logged in user** I can **unfollow another user** so that **I can stop seeing their events in my feed page**

## Acceptance Criteria:

* Acceptance Criteria 1: Once logged in, User can see an unfollow button next to each profile 
* Acceptance Criteria 2: Unfollow button visible on popular profiles list and on the profile page profile
* Acceptance Criteria 3: On click unfollow, logged in users following count decreases by 1
* Acceptance Criteria 4: On click unfollow, followed profile followed count goes down by 1

## Tasks:

- [ ] Design  unfollow button
- [ ] Create HTML, CSS, JSX - toggle button between follow/unfollow on click
- [ ] Create API requests - Create follow destroy request to API
- [ ] Test completed functionality
