### ISSUE TITLE
USER STORY: View review comments relating to a single event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#26]
As a **user** I can **see all the reviews relating to a single event** so that **I can see other user's opinions of the event after it happened**

## Acceptance Criteria:

* Acceptance Criteria 1: On clicking the review count number on the review page events list, a component appears below the selected event showing a list of all reviews which have been written about that event
* Acceptance Criteria 2: Reviews fields shown are : profile pic, username of review owner, created_at date, review and rating
* Acceptance Criteria 3: If no reivews have been written, a message shows that noone has reviewed this event yet.
* Acceptance Criteria 4: When another review is selected, other open review components disappear and a new one opens up

## Tasks:

- [ ] Design review component
- [ ] Create HTML, CSS, JSX - onclick button, component appears inside events list component under selected event, before next event
- [ ] Create API requests - request review list filtered by selected event in date created newest first order
- [ ] Test completed functionality
