### ISSUE TITLE
USER STORY: View events list filtered by event _ date 

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#27]
As a **user** I can **see all events that have happened** so that **I can see the reviews of people who attended the event**

## Acceptance Criteria:

* Acceptance Criteria 1: Filitered events by event date to be displayed on the reviews page
* Acceptance Criteria 2: Filter set to event_date where date is < today's date - ie. the date has passed, the event has happened
* Acceptance Criteria 3: Reviews can not be posted to events that have not happened yet

## Tasks:

- [ ] Design reviews page
- [ ] Create HTML, CSS, JSX - Use JSX to write date logic to filter out future dates from the list
- [ ] Create API requests - request events list filtered by event_date from API
- [ ] Test completed functionality
