### ISSUE TITLE
USER STORY: Create review

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#28]
As a **logged in user** I can **post a review on a past event** so that **I can share my opinion on the event**

## Acceptance Criteria:

* Acceptance Criteria 1: Once the user is logged in, in the reivews page, they can see a create review form on clickin on the review count button nect to an event
* Acceptance Criteria 2: Create review foms includes: review text field and 5 star rating system. Both fields are required fields to complete a successful review to the event.
* Acceptance Criteria 3: Install React rating component

## Tasks:

- [ ] Design review form
- [ ] Create HTML, CSS, JSX - style form and rating component
- [ ] Create API requests - post review to API
- [ ] Test completed functionality
