### ISSUE TITLE
USER STORY: Authentication - new users can sign up

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#29]
As a **user** I can **create a new user account** so that **experience the addititonal site features for users with accounts to log into**

## Acceptance Criteria:

* Acceptance Criteria 1: Onclick Sign up on the navbar, user can register an account
* Acceptance Criteria 2: Sign up page contains a sign up form with  username, password and password confirm field
* Acceptance Criteria 3: Validation in place on input fields
* Acceptance Criteria 4: Once user enters unique user information, new user account is created, 

## Tasks:

- [ ] Design sign up page
- [ ] Create HTML, CSS, JSX - bootstrap sign up form
- [ ] Create API requests - send create new user request to API
- [ ] Test completed functionality
