### ISSUE TITLE
USER STORY: Navigation Bar conditional rendering

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#3]
As a **user** I can **see the appropriate site access options** so that **I can easily access links to change my login status**

## Acceptance Criteria:

* Acceptance Criteria 1: If user is logged out, show login and signup links
* Acceptance Criteria 2: If user is logged in, show logout link
* Acceptance Criteria 3: When login status changes, login links automatically change too

## Tasks:

- [ ] Design logout icon
- [ ] Create HTML, CSS, JSX - Add conditional rendering logic to the navbar component
- [ ] Test completed functionality
