### ISSUE TITLE
USER STORY: View details of single event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#31]
As a **user** I can **see the details of a single event** so that **I can see everything relating to one event**

## Acceptance Criteria:

* Acceptance Criteria 1: Event page displays single event id details
* Acceptance Criteria 2: User, regardless of login status can view the event
* Acceptance Criteria 3: Event shows: image, title, description, created_at date, event_date, interested_count, going_count, comments_count, profile pic, username of user who posted it

## Tasks:

- [ ] Design Event Page
- [ ] Create HTML, CSS, JSX - style
- [ ] Create API requests - request single event ID
- [ ] Test completed functionality
