### ISSUE TITLE
USER STORY: Events list infinite scroll

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#34]
As a **user** I can **scroll endlessly through the events list** so that **I don't have to click 'next' to see more**

## Acceptance Criteria:

* Acceptance Criteria 1: Infinite scrolling set up on all events lists - home, feed, myevents, reviews
* Acceptance Criteria 2: Loads more events after every 10 posts
* Acceptance Criteria 3: Spinner shows while new events are loading

## Tasks:

- [ ] Design
- [ ] Create HTML, CSS, JSX - install infinite scroll
- [ ] Create API requests
- [ ] Test completed functionality
