### ISSUE TITLE
USER STORY: Alert - Confirm event deletion

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#35]
As a **user** I can **see a delete confirmation alert message** so that **I know my event has been removed from the site**

## Acceptance Criteria:

* Acceptance Criteria 1: - Alert message appears above the event container
* Acceptance Criteria 2: Alert message appears after an event has been successfully deleted from the database
* Acceptance Criteria 3: Alert message automatically disappears after 3 seconds.

## Tasks:

- [ ] Design - Bootstrap alert
- [ ] Create HTML, CSS, JSX - Create Alert component and pass it down into the Event.js as a child component
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
Individual alert succesfully created for sending a message - Now i want to convert the alert into a more generic separate re-usable component to be used across multiple areas, instead of setting up a new alert in each individual component.
