### ISSUE TITLE
USER STORY: View 5 most popular profiles

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#36]
As a **user** I can **see the most popular profiles** so that **I know which popular profiles to check out**

## Acceptance Criteria:

* Acceptance Criteria 1: Definition of popular profile = count of followers in order from highest to lowest - display five profiles with highest number of followers.
* Acceptance Criteria 2: Popular Profiles container to be displayed on all pages above the events posts.
* Acceptance Criteria 3: When current logged in user changes, refresh popular profiles list. 

## Tasks:

- [ ] Design - container
- [ ] Create HTML, CSS, JSX - style with profile avatar and username
- [ ] Create API requests - get profiles ordered by followers_count in descemnding order
- [ ] Test completed functionality
