### ISSUE TITLE
USER STORY: View most popular events

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#37]
As a **user** I can **see the top 10 events** so that **I can consider going to these popular events**

## Acceptance Criteria:

* Acceptance Criteria 1: Definition of top events = Order events in order of going_count. The 10 events with the highest number of going_count will be displayed
* Acceptance Criteria 2: Top events container to be displayed next to the events post list in desktop and tablet view, and above the events in mobile view.
* Acceptance Criteria 3: User will see the event title, and event_date
* Acceptance Criteria 4: Popular events list to be refreshed each time the logged in user changes. 
* Acceptance Criteria 5: Popular events list to be displayed on all pages

## Tasks:

- [ ] Design
- [ ] Create HTML, CSS, JSX
- [ ] Create API requests
- [ ] Test completed functionality
