### ISSUE TITLE
USER STORY: View a profile page

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#38]
As a **user** I can **view the profile page of another user** so that **I can see more details about that user**

## Acceptance Criteria:

* Acceptance Criteria 1: Profile page includes all additional profile model fields - bio, name, email, website, social medial links,
* Acceptance Criteria 2: Profile page also includes followers count, followed count, events posted count and events going count.
* Acceptance Criteria 3: Profile can be viewed by all users 

## Tasks:

- [ ] Design
- [ ] Create HTML, CSS, JSX
- [ ] Create API requests
- [ ] Test completed functionality
