### ISSUE TITLE
USER STORY: Edit a profile page

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#39]
As a **logged in user** I can **edit my own profile page** so that **I can add additional information for other users to see about me**

## Acceptance Criteria:

* Acceptance Criteria 1: Add EditDelete Component dropdown to the profile page
* Acceptance Criteria 2: Only show the edit dropdown when the user is logged in, and if the logged in username matches the profile username.
* Acceptance Criteria 3: User can edit all fields of the profile

## Tasks:

- [ ] Design - Profile page edit form
- [ ] Create HTML, CSS, JSX - Link to edit component
- [ ] Create API requests - call put request to update existing profile instance
- [ ] Test completed functionality
