### ISSUE TITLE
USER STORY: Authentication - login

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#4]
As a **user** I can **log into the app** so that **I can access full site functionality**

## Acceptance Criteria:

* Acceptance Criteria 1: Login link accesible in the navbar to logged out users
* Acceptance Criteria 2: Login link takes user to enter credentials and login to site
* Acceptance Criteria 3: After login, user redirected to homepage

## Tasks:

- [ ] Create HTML, CSS, JSX - for login page
- [ ] Create API requests - send request to API dj-auth to check credentials
- [ ] Test completed functionality
