### ISSUE TITLE
USER STORY: Edit username and password

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#40]
As a **user** I can **change my username and password** so that **I can change my login details if I feel they are not secure**

## Acceptance Criteria:

* Acceptance Criteria 1: - Edit username and password buttons to appear on the profile page
* Acceptance Criteria 2: Only a logged in user can update their own username and password, noone elses
* Acceptance Criteria 3: The edit form will appear inside a modal popup

## Tasks:

- [ ] Design - edit modal component
- [ ] Create HTML, CSS, JSX - Add a form inside the modal to input the new details
- [ ] Create API requests - send a put request to the user model
- [ ] Test completed functionality
