### ISSUE TITLE
USER STORY: View reviews relating to one event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#41]
As a **user** I can **view reviews of an event after it has taken place** so that **I can see how other users rated the event**

## Acceptance Criteria:

* Acceptance Criteria 1: On Reviews page, view list of all reviews relating to that event under the event listing -
* Acceptance Criteria 2: Review detail inclue: Star rating , comments
* Acceptance Criteria 3: Review comments initially hidden. Only star rating can be seen to start with . Then if user clicks on the review count link, the comments component opens up 

## Tasks:

- [ ] Design - Reviews page
- [ ] Create HTML, CSS, JSX - Review events list component, star rating component, review comments component
- [ ] Create API requests - send request for reviews to the API and events
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
duplicate user story - see #26
