### ISSUE TITLE
USER STORY: Edit review

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#42]
As a **logged in user** I can **edit my own reviews** so that **I can correct my comments or change my rating**

## Acceptance Criteria:

* Acceptance Criteria 1: If user is logged in, and the review belongs to them, the edit button is available next to the review
* Acceptance Criteria 2: If user selects edit, review edit form is opened up and pre-populated with review details and rating.
* Acceptance Criteria 3: On save, the existing review is updated and seen on screen

## Tasks:

- [ ] Design edit review form page - in a popup modal as it's only two fields
- [ ] Create HTML, CSS, JSX -  pre-populate review form for editing
- [ ] Create API requests - put request to the API
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
User can now only edit the review comment, not the star rating. If they wish to review the star rating, they see a message saying they must delete the entire review and start again from scratch, as it seems the star rating review component that npm have created does not work well being edited.
