### ISSUE TITLE
USER STORY: Delete review

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#43]
As a **logged in user** I can **delete a review that I created** so that **I can remove reviewsI no longer want published**

## Acceptance Criteria:

* Acceptance Criteria 1: Once logged in, user can see the delete button next to all the reviews that they created
* Acceptance Criteria 2: Delete button asks for confirmation - for defensive design - modal- delete confirmation
* Acceptance Criteria 3: Once confirmed deletion, review is removed from the review list and deleted from the database, and review count and avg_rating are updated on screen

## Tasks:

- [ ] Design - Delete button - links to editdelete dropdown and deleteconfirmation modal
- [ ] Create HTML, CSS, JSX - Add in extra buttons and message for deletemodal
- [ ] Create API requests - destroy request to API
- [ ] Test completed functionality
