### ISSUE TITLE
USER STORY: View event list with star ratings

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#44]
As a **user** I can **see the star ratings added against all past events** so that **I can see the average ratings for all events that have happened**

## Acceptance Criteria:

* Acceptance Criteria 1: Reviews Page shows a list of all events where the event_date is today or less
* Acceptance Criteria 2: Each event listed shows the following fields; event title, event_date, avergage_rating and review_count. 
* Acceptance Criteria 3: Review count field is clickable to show the review comments below the selecte event. 

## Tasks:

- [ ] Design - Events list component
- [ ] Create HTML, CSS, JSX - filter events list on the frontend for <= todays date
- [ ] Create API requests - request the events list ordered by event_date in descending order
- [ ] Test completed functionality
