### ISSUE TITLE
USER STORY: View user friendly date format

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#46]
As a **user** I can **read the date in a user friendly way** so that **I don't have to decipher which is the day, month and year**

## Acceptance Criteria:

* Acceptance Criteria 1: - Set up date formatter component - to change date to format: day (number) , month (written month name), full year (numbers)
* Acceptance Criteria 2: Affects the following components - Popular Events, Event.js, review.js
* Acceptance Criteria 3:

## Tasks:

- [ ] Design - date formatter component
- [ ] Create HTML, CSS, JSX - import formatter into necessary places where event_date is displayed
- [ ] Test completed functionality
