### ISSUE TITLE
USER STORY: Create message 

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#49]
As a **logged in user** I can **send a message to another user** so that **I can ask a question about an event they are hosting**

## Acceptance Criteria:

* Acceptance Criteria 1: Message form to appear in the profile page of the user you want to send the message to.
* Acceptance Criteria 2: Message form to contain one input field: message
* Acceptance Criteria 3: Send button sends message to API
* Acceptance Criteria 4: Success Alert tells user message has been sent successfully

## Tasks:

- [ ] Design message form
- [ ] Create HTML, CSS, JSX - Set up form in the profile page top right hand corner
- [ ] Create API requests - API post request to /contact
- [ ] Test completed functionality
