### ISSUE TITLE
USER STORY: Authentication - logout

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#5]
As a **user** I can **log out of the app** so that **I can stop accessing full site functionality on my device while not actively contributing to the site**

## Acceptance Criteria:

* Acceptance Criteria 1: Logout link accesible in the navbar to logged in users
* Acceptance Criteria 2: Logout link logs user out of the site
* Acceptance Criteria 3: After logout, user redirected to homepage

## Tasks:

- [ ] Create HTML, CSS, JSX - for logout page
- [ ] Create API requests - send request to API dj-auth to log user out
- [ ] Test completed functionality
