### ISSUE TITLE
USER STORY: View messages

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#50]
As a **logged in user** I can **view messages in my profile page** so that **I can read messages other users have sent me**

## Acceptance Criteria:

* Acceptance Criteria 1: Received messages appear in the profile page in the top right hand corner
* Acceptance Criteria 2: In your own profile page, you see the received messages component, and you can't see the send message form as you can't send messages to yourself. 
* Acceptance Criteria 3: Messages appear in a list in reverse date order

## Tasks:

- [ ] Design messages list
- [ ] Create HTML, CSS, JSX - if profile owner, show received messages component, if not profile owner see send message form
- [ ] Create API requests - Get Messages where profile they are sent to matches profile page id
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
Result of checks... I forgot to include a filter in the backend to give the functionality to filter all messages by profile ID the message has been sent to. Fix to be done on the backend.
