### ISSUE TITLE
USER STORY: Avatar

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#6]
As a **user** I can **see the avatar image of each user** so that **I can easily distiguish between different site users**

## Acceptance Criteria:

* Acceptance Criteria 1: Default avatar assigned to all users on signup
* Acceptance Criteria 2: In profile, users can upload personalised avatar image
* Acceptance Criteria 3: Avatar displayed next to all personally created items in the site - comments, events, reviews, profile
* * Acceptance Criteria 4: Avatar shown next to profile in popular profiles list

## Tasks:

- [ ] Design default avatar img
- [ ] Create HTML, CSS, JSX - set avatar next to posts for event, comment, review and in the user profile page. 
- [ ] Create API requests
- [ ] Test completed functionality
