### ISSUE TITLE
USER STORY: View list of all events 

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#7]
As a **user** I can **see a list of all events** so that **I can see all events that have been shared to the site**

## Acceptance Criteria:

* Acceptance Criteria 1: Homepage displays list of all events posted to the site
* Acceptance Criteria 2: User, regardless of login status can view all events
* Acceptance Criteria 3: Events show: image, title, description, created_at date, event_date, interested_count, going_count, comments_count, profile pic, username of user who posted it
* Acceptance Criteria 4: List of events ordered by created_at , most recent first

## Tasks:

- [ ] Design Posts Page
- [ ] Create HTML, CSS, JSX
- [ ] Create API requests
- [ ] Test completed functionality
