### ISSUE TITLE
USER STORY: View events of followed profiles

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#8]
As a **user** I can **see events feed** so that **I can only see events of profiles I follow**

## Acceptance Criteria:

* Acceptance Criteria 1: Filter events by followed profiles
* Acceptance Criteria 2: Only display events in the filter results 
* Acceptance Criteria 3: Display the results in a 'popular events' component at the side of the homepage, feed and my events page

## Tasks:

- [ ] Design
- [ ] Create HTML, CSS, JSX - create popular events component
- [ ] Create API requests - get filtered events by followed profiles list
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
Now that the follow and unfollow functions workk, i#ve tested the feed events pulling through and the filter is working correctly, to show only the posts of the users followed.
