### ISSUE TITLE
USER STORY: View events that user is going to or interested in

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/happening-react-frontend#9]
As a **user** I can **see my events** so that **I can see only the events i'm interested in or going to**

## Acceptance Criteria:

* Acceptance Criteria 1: Filter events by events that have an interested id linked to the logged in user, or a going id linked to the logged in user.
* Acceptance Criteria 2: Only display events in the filter results 
* Acceptance Criteria 3: Display the results in the 'my events' page

## Tasks:

- [ ] Design
- [ ] Create HTML, CSS, JSX - Create my events route in APP.js, 
- [ ] Create API requests - try to add the two API filters together to display interested AND going to events in the events list 
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
Only working for the interested filter at the moment. Need to figure out how to add in going posts as well.

**Comment by quiltingcode** [comment]
It doesn't seem like this is possible to combine two filters, either on the backend or the frontend.
I've have asked on slack and even the channel leads can not help with a solution to this. 
So i have decidede to add an additional toggle filter so that the user can switch between seeing all interested events OR all going events, but not both combined.
